apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: zvlz15k8l-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:23e4b7baf6ebe500281a64153d6a7f3e4f283bc1@sha256:8bd8c175a53d3b9cd76ce4064490fef8ac5f46ab0407b6d0427b43697e669c83
          name: container-image
